import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "@/styles/globals.css";
import Header from "@/components/Header";


const roboto = Roboto({ display: "swap", subsets: ["latin-ext"], weight: ["300", "400", "500", "700", "900"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">

      <body className={roboto.className}>
        <Header />

        {children}
      </body>
      
    </html>
  );
}